// Alert Context
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Auth Context
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// Profile Context
export const SET_PROFILE = 'SET_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE'
export const SET_OTHER_PROFILE = 'SET_OTHER_PROFILE'
export const FETCHING_PROFILE = 'FETCHING_PROFILE'
export const SET_SERVICES = 'SET_SERVICES'
export const FOLLOW_USER = 'FOLLOW_USER'
export const UNFOLLOW_USER  = 'UNFOLLOW_USER'


// Search Context
export const SEARCH_USERS = 'SEARCH_USERS';
export const GET_VIEWING_USER = 'GET_VIEWING_USER';
export const SEARCHING_FOR_RESULTS = 'SEARCHING_FOR_RESULTS';
export const CLEAR_VIEWING_USER = 'CLEAR_VIEWING_USER';
export const CLEAR_SEARCH_STATE = 'CLEAR_SEARCH_STATE';

// Post Context
export const UPDATE_LAST_POST = 'UPDATE_LAST_POST';
export const UPDATE_POSTS = 'UPDATE_POSTS';
export const SET_POSTS = 'SET_POSTS';
export const FIND_FOLLOWING_POSTS = 'FIND_FOLLOWING_POSTS';
export const GET_NEWSFEED = 'GET_NEWSFEED';
export const GET_OTHER_POSTS = 'GET_OTHER_POSTS';
export const REMOVE_POST = 'REMOVE_POST';
export const CLEAR_POST_STATE = 'CLEAR_POST_STATE';
export const UPDATE_LIKES = 'UPDATE_LIKES';
export const CLEAR_OTHER_POSTS = 'CLEAR_OTHER_POSTS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
export const UPDATE_COMMENT_LIKES = 'UPDATE_COMMENT_LIKES';
export const GET_POSTS = 'GET_POSTS';
export const UPDATE_COMMENT_REPLY = 'UPDATE_COMMENT_REPLY';
export const UPDATE_COMMENT_REPLY_LIKES = 'UPDATE_COMMENT_REPLY_LIKES';
export const REMOVE_REPLY = 'REMOVE_REPLY';
export const GET_PAGE_POSTS = 'GET_PAGE_POSTS';


// Page Context 
export const SET_PAGE = 'SET_PAGE';
export const SET_CURRENT_PAGE_ROLE = 'SET_CURRENT_PAGE_ROLE'
export const SET_MY_PAGE = 'SET_MY_PAGE';
export const SET_MY_PAGE_FAIL = 'SET_MY_PAGE_FAIL'
export const SET_CURRENT_PACKAGE = 'SET_CURRENT_PACKAGE'
export const SERVICE_BOUGHT = 'SERVICE_BOUGHT'
export const SET_TRAINERS = 'SET_TRAINERS'
